---
title: "Data Set Introduction"
---
<center><small> Shuting Ouyang E1329489 </small></center>
<center><small><em>The data set is <strong>World Happiness Report</strong> from Kaggle.</em></small></center>

<br>
<div style="text-align: justify;">
<p>Global Happiness Report reviews Happiness data from 2012 to now. It collects about 1000 reply every year from about 130~150 countries. The Happiness Ranking based on <strong>The Gallup World Poll</strong> score averaged in the nearest 3 years. This Poll ask participants to imagine their best and poorest possible life, then answer where are they at, giving a score 0, the worst, to 10, the best.</p>

<p>Then the happiness report analysis the happiness data with 6 indicators. They are GDP per capita, perceived social support, health life expectancy, freedom in life, generosity and perception of corruption.</p>
</div>
<small><em><center>*Please Note: These are not factors deciding the Happiness level (aka Ladder Score), these are factors we explore to identify their relationship with Happiness level.</center></em></small>

<ol>
  <li>GDP is calculated using Purchasing Power Parity (PPP) and World Development Indicators (WDI).</li>
  <br>
  <li>Health Life Expectancy came from World Health Organization (WHO) and WDI.</li>
  <br>
  <li>Social Support comes from this question: "<strong>If you were in trouble, do you have relatives or friends you can count on to help you whenever you need them, or not?</strong>" 1 = Have , 0 = Don’t have.</li>
  <br>
  <li>Freedom in Life comes from this question: "<strong>“Are you satisfied or dissatisfied with your freedom to choose what you do with your life?”</strong>" 1 = Satisfied, 0 = Not Satisfied.</li>
  <br>
  <li>Generosity comes from this question: "<strong>Have you donated money to a charity in the past month</strong>? " 1 = Yes, 0 = No.</li>
  <br>
  <li>Perceptions of corruption/Trust in organization comes from 2 questions: "<strong>Is corruption widespread throughout the government or not?</strong>" and "<strong>Is corruption widespread within businesses or not?</strong>". 1= Trust, 0 = No Trust.</li>
</ol>

<p>Then, these 6 factors data will adjust to a factor which set the lowest average score ever get in the survey to 0. Each year's data would be a representation of the previous year, for example, the 2024 data, is actually analyzing 2023</p>

<p>More detailed information can be found in "<em>World Happiness Report 2024 Chapter 2 Appendix 1</em>".</p>
